### ISSUE TITLE
Crash from keyboard navigation after transitioning from a scene.

### ISSUE THREAD

**Issue by dch-GH** [mestiez/Walgelijk#13]
```Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '476563243' was not present in the dictionary.
   at Walgelijk.Onion.Navigator.ProcessKeyboardNavigation(Input input) in O:\Projects\Walgelijk\Walgelijk.Onion\Navigator.cs:line 207
   at Walgelijk.Onion.Navigator.Process(Input input, Single dt) in O:\Projects\Walgelijk\Walgelijk.Onion\Navigator.cs:line 130
   at Walgelijk.Onion.OnionSystem.Update() in O:\Projects\Walgelijk\Walgelijk.Onion\OnionSystem.cs:line 35
   at Walgelijk.Game.Start() in O:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 146
   at MIR.Entry..ctor() in S:\sdev\MadnessInteractiveReloaded\src\MadnessInteractiveReloaded\Entry.cs:line 119
   at MIR.Program.Main(String[] args) in S:\sdev\MadnessInteractiveReloaded\src\MadnessInteractiveReloaded\Program.cs:line 16
   ```

1. Open an Onion UI scene.
2. Leave the scene/return to main menu
3. Press arrow key
4. Crash

**Comment by mestiez** [comment]
fixed a year later #10xdev
